name: racebox_simulator
description: Standalone simulator for Racebox BLE devices
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.4.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_lints: ^6.0.0

